### ISSUE TITLE
Runtime Error Object doesn't support property or method 'spin'

### ISSUE THREAD

**Issue by LordDraagonLive** [LordDraagonLive/Slot_Machine_Ionic#2]
The error comes when the spin button is pressed (Avoid pressing other buttons as there are not implemented). 'Spin' function will change the 3 image slots using a 'setInterval' function.

Error Stack ;
TypeError: Object doesn't support property or method 'spin'
   at Anonymous function (Function code:76:15)
   at handleEvent (http://localhost:8100/build/vendor.js:13607:87)
   at callWithDebugContext (http://localhost:8100/build/vendor.js:15092:9)
   at debugHandleEvent (http://localhost:8100/build/vendor.js:14679:5)
   at dispatchEvent (http://localhost:8100/build/vendor.js:10056:9)
   at Anonymous function (http://localhost:8100/build/vendor.js:10670:31)
   at Anonymous function (http://localhost:8100/build/vendor.js:36360:9)
   at t.prototype.invokeTask (http://localhost:8100/build/polyfills.js:3:15536)
   at onInvokeTask (http://localhost:8100/build/vendor.js:4970:17)
   at t.prototype.invokeTask (http://localhost:8100/build/polyfills.js:3:15536)
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.0
Angular Core: 5.0.0
Angular Compiler CLI: 5.0.0
Node: 8.7.0
OS Platform: Windows 10
Navigator Platform: Win32

**Comment by LordDraagonLive** [comment]
The above error was fixed. The error occurred because the 'spin()' function was created outside of GamePage class. To fix the issue I created a function called 'ionicSpin()' in GamePage class and called the 'spin()' method of Reel class inside the  'ionicSpin()' function.
